### ISSUE TITLE
How to import the components - create-react-app - react 16.2.0

### ISSUE THREAD

**Issue by mrcoles** [crobinson42/react-skeleton-css#1]
I have a react app running react 16.2.0. I installed the package:

```
npm i -S react-skeleton-css
```

In my App.js file I did this import:

```
import Skeleton, { Input } from 'react-skeleton-css';
```

If I `console.log` those, I see:

*   `Skeleton` is an empty object
*   `Input` is `undefined`

**Comment by crobinson42** [comment]
Hi @mrcoles I haven't had time to upgrade react to v16 in the library, yet. PR's are welcome!

**Comment by mrcoles** [comment]
I ended up just switching to vanilla skeleton and writing my own components. If I revisit, I’ll give it a go! 😎
