### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by alaxcc** [crobinson42/react-skeleton-css#6]
import css,and then?

I try <Button>Button</Button>,and it's error.

**Comment by crobinson42** [comment]
What version of React are you using as well as the code and the error?

**Comment by ericnakagawa** [comment]
I also have an issue using this. The instructions say to import the css, but there doesn't seem to be an import for the components themselves.

**Comment by ericnakagawa** [comment]
I also have an issue using this. The readme says to import the css, but doesn't explain how to import the components themselves.

**Comment by crobinson42** [comment]
Does this work?

```
import {
  Container,
  Column,
  Row,
  Table,
  Button,
  Link
} from 'react-skeleton-css'
```
